// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function BeginEdit():Promise<core.LockState>;

export function CancelEdit():Promise<void>;

export function CheckExternal():Promise<core.ExternalState>;

export function ChooseDictionaryFile():Promise<string>;

export function ClearLock():Promise<void>;

export function CurrentPath():Promise<string>;

export function GetPreferences():Promise<core.Preferences>;

export function History():Promise<Array<core.HistoryEntry>>;

export function HistoryContent(arg1:string):Promise<string>;

export function HistorySummary(arg1:string):Promise<string>;

export function LockState():Promise<core.LockState>;

export function MasterFileName():Promise<string>;

export function OpenDictionary(arg1:string):Promise<core.LoadResult>;

export function ReloadDictionary():Promise<core.LoadResult>;

export function RestoreVersion(arg1:string):Promise<core.LoadResult>;

export function SaveDictionary(arg1:core.Document):Promise<core.SaveResult>;

export function SetTheme(arg1:string):Promise<void>;

export function ValidateDictionary(arg1:core.Document):Promise<Array<core.Finding>>;
