// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginEdit() {
  return window['go']['main']['App']['BeginEdit']();
}

export function CancelEdit() {
  return window['go']['main']['App']['CancelEdit']();
}

export function CheckExternal() {
  return window['go']['main']['App']['CheckExternal']();
}

export function ChooseDictionaryFile() {
  return window['go']['main']['App']['ChooseDictionaryFile']();
}

export function ClearLock() {
  return window['go']['main']['App']['ClearLock']();
}

export function CurrentPath() {
  return window['go']['main']['App']['CurrentPath']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function HistoryContent(arg1) {
  return window['go']['main']['App']['HistoryContent'](arg1);
}

export function HistorySummary(arg1) {
  return window['go']['main']['App']['HistorySummary'](arg1);
}

export function LockState() {
  return window['go']['main']['App']['LockState']();
}

export function MasterFileName() {
  return window['go']['main']['App']['MasterFileName']();
}

export function OpenDictionary(arg1) {
  return window['go']['main']['App']['OpenDictionary'](arg1);
}

export function ReloadDictionary() {
  return window['go']['main']['App']['ReloadDictionary']();
}

export function RestoreVersion(arg1) {
  return window['go']['main']['App']['RestoreVersion'](arg1);
}

export function SaveDictionary(arg1) {
  return window['go']['main']['App']['SaveDictionary'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ValidateDictionary(arg1) {
  return window['go']['main']['App']['ValidateDictionary'](arg1);
}
